# TIMES
FLEX_TIMEOUT = 15
AMPEL_TIMEOUT = 1
DSO_EMPTY_WAIT = 1
SIM_TIME = 1440
CHARGING_INTERVALL = 15
MARKET_TIMEOUT = 1

# DISTRIBUTION TIME
START_MEAN = 180
START_SD = 90
END_MEAN = 1020
END_SD = 150

# CAR
SOC_FULL = 100
WALLBOX_CAP = 11
PREFERENCE = range(0, 10, 1)
SOC_MEAN = 65
SOC_SD = 20

# GRID
DSO_CAP = 3000
DEMAND = []
AMPEL_TRESHOLD = 0.3*DSO_CAP

# MARKET
REG_ELEC_PRICE = 0.30
MERIT_ORDER_TIMESERIES = [0]
FLEX_OFFER_LEVEL = 1
ALL_BIDS = []
SELECTED_BIDS = []
